#!/bin/bash -x
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -e

#
# Ensure Kraftwagen is installed
#
[ -d ${OPENSHIFT_HOMEDIR}.drush/kraftwagen ] || {
  echo "Installing Kraftwagen"
  cd ${OPENSHIFT_HOMEDIR}.drush
  git clone git://github.com/kraftwagen/kraftwagen.git
  drush cc drush
}

#
# Kraftwagen setup
#
[ -d "${OPENSHIFT_REPO_DIR}cnf" ] || {
  cd ${OPENSHIFT_REPO_DIR}src
  drush kw-s
}

#
# Kraftwagen build
#
[ -L "${OPENSHIFT_REPO_DIR}build" ] || {
  cd ${OPENSHIFT_REPO_DIR}src
  drush kw-b
}

#
# Symlinks
#
rm -rf ${OPENSHIFT_REPO_DIR}php
ln -s ${OPENSHIFT_REPO_DIR}build ${OPENSHIFT_REPO_DIR}php

#
# Patches
#
cd ${OPENSHIFT_REPO_DIR}php
patch -p0 -i ${OPENSHIFT_REPO_DIR}patches/update_htaccess_for_apache_2_4-1599774-25.patch .htaccess

#
# Initialize DB
#
( drush sql-query "SELECT * FROM users WHERE uid=1" && drush kw-u ) || {
  drush kw-id
}
