#!/bin/bash -x
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc. 

set -e

#
# Ensure Kraftwagen is installed
#
[ -d ${OPENSHIFT_HOMEDIR}.drush/kraftwagen ] || {
  echo "Installing Kraftwagen"
  cd ${OPENSHIFT_HOMEDIR}.drush
  git clone git://github.com/kraftwagen/kraftwagen.git
  drush cc drush
}

#
# Kraftwagen setup
#
[ -d "${OPENSHIFT_REPO_DIR}cnf" ] || {
  cd ${OPENSHIFT_REPO_DIR}src
  drush kw-s
}

#
# Kraftwagen initial build
#
[ -L "${OPENSHIFT_REPO_DIR}build" ] || {
  cd ${OPENSHIFT_REPO_DIR}src
  drush kw-b
}