#!/bin/bash -x
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc. 

set -e

#
# Initialize DB
#
[ drush sql-query "SELECT * FROM users WHERE uid=1" ] || {
  drush kw-id
}