#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

set -e

cd ${OPENSHIFT_REPO_DIR}php

#
# Initialize DB
#
( drush sql-query "SELECT * FROM users WHERE uid=1" ) || {
  drush kw-id
}

#
# Update
#
drush kw-u